### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by maciekkoz98** [DanielSporysz/youtube-dl-format-autopicker#1]
Hey!
I just encountered a spelling mistake in your so-called smart shell script.
Line 12 'foramt' instead of 'format'
I strongly recommend you to fix this issue.
Best wishes,
Maciej

**Comment by DanielSporysz** [comment]
Hi Maciej, 

I'd like to thank you for your contribution to this project. I have taken all the necessary steps to address the issue and provide you with a product of the quality that you truly deserve. Should you have any comments left, please ask them straight away! If not, then consider the issue done and accept the pull request.

Sincerely,
Daniel

**Comment by maciekkoz98** [comment]
I'm quite surprised that you added me to the repository in order to resolve this issue. Changes that you provided are good and they should be merged into the master branch but I don't think that I'm the right person to do this. I don't find myself a proper member of the project. I just found a bug and reported it.
I would feel better if you were the person fully responsible for your code. 
Best wishes,
Maciej

**Comment by DanielSporysz** [comment]
I'm pleased to have this conversation with such a humble person as yourself. I wouldn't dare to take any credit for the issue that you have found but if that is your decision, I will do everying that is in my power to honor it.

Cheers, 
Daniel
